# Generated by Django 4.2.13 on 2024-05-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ogloszenie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tytul", models.CharField(max_length=100)),
                ("tresc", models.TextField()),
                ("data_publikacji", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
